image: python:3.7-alpine

test:
  stage: test
  script:
  - apk --no-cache add make
  - pip install -U sphinx
  - make html
  - mv _build/html/ public/
  only:
  - branches
  except:
  - master

pages:
  stage: deploy
  script:
  - apk --no-cache add make
  - pip install -U sphinx
  - make html
  - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
